[2019-05-22 12:48:22,029][MainThread:10928][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 12:48:47,737][Thread-1:20176][task_id:mockapp.views][views.py:24][ERROR][UNIQUE constraint failed: auth_user.username]
[2019-05-22 12:50:26,945][MainThread:10928][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 12:50:34,406][MainThread:16716][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 12:50:46,107][Thread-1:14964][task_id:mockapp.views][views.py:27][ERROR][UNIQUE constraint failed: auth_user.username]
[2019-05-22 12:51:46,684][MainThread:16716][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 12:51:49,980][MainThread:15884][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 12:55:53,226][MainThread:1500][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 12:57:01,878][MainThread:1500][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 12:57:04,775][MainThread:20472][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 12:58:02,135][Thread-1:19440][task_id:django.request][log.py:228][WARNING][Method Not Allowed (POST): /mock/user/queryAll]
[2019-05-22 12:59:33,395][MainThread:20472][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 12:59:35,919][MainThread:9172][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:07:18,768][MainThread:9172][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 13:07:22,125][MainThread:17604][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:10:10,828][MainThread:17604][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 13:10:14,049][MainThread:7252][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:40:42,363][MainThread:20436][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:41:24,358][MainThread:2548][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:42:41,549][Thread-1:16140][task_id:django.request][log.py:228][WARNING][Method Not Allowed (GET): /mock/login]
[2019-05-22 13:42:46,662][Thread-1:16140][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/login]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 59, in login
    return success_jsonresponse("登入成功",100000,data=user)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 8, in success_jsonresponse
    data = queryset_to_dict(data)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 28, in queryset_to_dict
    js=serializers.serialize("json", queryset, ensure_ascii=False)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\serializers\__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\serializers\base.py", line 90, in serialize
    for count, obj in enumerate(queryset, start=1):
TypeError: 'User' object is not iterable
[2019-05-22 13:45:16,312][MainThread:2548][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\utils\common.py changed, reloading.]
[2019-05-22 13:45:18,695][MainThread:19668][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:45:45,093][MainThread:19668][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\utils\common.py changed, reloading.]
[2019-05-22 13:45:47,789][MainThread:17760][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:45:50,382][MainThread:17760][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\utils\common.py changed, reloading.]
[2019-05-22 13:45:52,701][MainThread:20036][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:46:00,916][MainThread:20036][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\utils\common.py changed, reloading.]
[2019-05-22 13:46:03,144][MainThread:14372][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:46:33,082][MainThread:4800][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:46:38,403][Thread-1:19764][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/login]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 59, in login
    return success_jsonresponse("登入成功",100000,data=user)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 11, in success_jsonresponse
    jsonstr = json.dumps(responsedict,ensure_ascii=False)
  File "C:\python\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\python\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'User' is not JSON serializable
[2019-05-22 13:47:24,963][MainThread:15568][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:47:29,277][Thread-1:10212][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/login]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 59, in login
    return success_jsonresponse("登入成功",100000,data=user)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 13, in success_jsonresponse
    jsonstr = json.dumps(responsedict,ensure_ascii=False)
  File "C:\python\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\python\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable
[2019-05-22 13:53:36,774][MainThread:20352][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:53:46,525][MainThread:19000][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:54:45,482][MainThread:19000][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\utils\common.py changed, reloading.]
[2019-05-22 13:54:48,151][MainThread:10992][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 13:55:44,783][Thread-1:17452][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/login]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 59, in login
    return success_jsonresponse("登入成功",100000,data=user)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 13, in success_jsonresponse
    jsonstr = json.dumps(responsedict,ensure_ascii=False)
  File "C:\python\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\python\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable
[2019-05-22 14:00:05,213][MainThread:10992][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:00:08,051][MainThread:3340][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:00:21,180][Thread-1:20368][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/login]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 59, in login
    return success_jsonresponse("登入成功",100000,data={"username":user.username,"email":user.email})
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 11, in success_jsonresponse
    data = object_to_json(data)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 29, in object_to_json
    return dict([(kk, obj.__dict__[kk]) for kk in obj.__dict__.keys() if kk != "_state"])
AttributeError: 'dict' object has no attribute '__dict__'
[2019-05-22 14:00:32,359][Thread-1:20368][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/login]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 59, in login
    return success_jsonresponse("登入成功",100000,data={"username":user.username,"email":user.email})
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 11, in success_jsonresponse
    data = object_to_json(data)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 29, in object_to_json
    return dict([(kk, obj.__dict__[kk]) for kk in obj.__dict__.keys() if kk != "_state"])
AttributeError: 'dict' object has no attribute '__dict__'
[2019-05-22 14:01:03,929][MainThread:3340][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\utils\common.py changed, reloading.]
[2019-05-22 14:01:06,344][MainThread:396][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:03:35,241][MainThread:396][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:03:37,427][MainThread:18400][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:04:10,032][MainThread:18400][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:04:12,993][MainThread:20472][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:04:57,619][MainThread:20472][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:05:00,234][MainThread:20284][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:06:14,946][MainThread:20284][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:06:16,842][MainThread:15048][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:06:31,840][Thread-1:3256][task_id:django.request][log.py:228][WARNING][Method Not Allowed (POST): /mock/user/queryAll]
[2019-05-22 14:06:39,734][Thread-1:3256][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/user/queryAll]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 48, in query_all_user
    logger.info("查询成功,结果集:\n"+users)
TypeError: must be str, not QuerySet
[2019-05-22 14:08:38,305][MainThread:15048][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:08:40,402][MainThread:16728][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:09:10,494][Thread-1:19000][task_id:mockapp.views][views.py:48][INFO][查询成功]
[2019-05-22 14:09:56,089][MainThread:16728][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:09:58,478][MainThread:18424][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:10:02,766][Thread-1:18728][task_id:mockapp.views][views.py:48][INFO][查询成功]
[2019-05-22 14:10:23,097][Thread-1:18728][task_id:mockapp.views][views.py:48][INFO][查询成功]
[2019-05-22 14:10:25,923][Thread-1:18728][task_id:mockapp.views][views.py:48][INFO][查询成功]
[2019-05-22 14:13:26,756][MainThread:18424][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\settings.py changed, reloading.]
[2019-05-22 14:13:29,595][MainThread:14260][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:13:34,083][Thread-1:14404][task_id:mockapp.views][views.py:48][INFO][查询成功]
[2019-05-22 14:15:11,241][MainThread:14260][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\mock_url.py changed, reloading.]
[2019-05-22 14:15:13,360][MainThread:312][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:15:51,088][Thread-1:19520][task_id:mockapp.views][views.py:49][INFO][查询成功]
[2019-05-22 14:20:58,301][Thread-1:19520][task_id:django.request][log.py:228][WARNING][Not Found: /mock/user/mock/login/]
[2019-05-22 14:22:02,472][MainThread:312][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\mock_url.py changed, reloading.]
[2019-05-22 14:22:05,012][MainThread:17872][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:24:15,810][MainThread:17872][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:24:18,204][MainThread:10664][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:24:58,804][MainThread:20268][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:25:06,959][Thread-1:20152][task_id:django.request][log.py:228][WARNING][Not Found: /mock/user/mock/loginmsg/]
[2019-05-22 14:25:37,496][MainThread:20268][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:25:39,343][MainThread:13944][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:25:57,188][Thread-1:11596][task_id:django.request][log.py:228][WARNING][Not Found: /mock/user/mock/loginmsg]
[2019-05-22 14:26:33,466][MainThread:13944][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\mock_url.py changed, reloading.]
[2019-05-22 14:26:35,646][MainThread:7364][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:26:48,953][Thread-1:20048][task_id:django.request][log.py:228][WARNING][Not Found: /mock/user/mock/loginmsg]
[2019-05-22 14:26:58,011][Thread-1:20048][task_id:django.request][log.py:228][WARNING][Not Found: /mock/user/mock/loginmsg/]
[2019-05-22 14:27:26,053][MainThread:7364][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\mock_url.py changed, reloading.]
[2019-05-22 14:27:28,138][MainThread:15948][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:27:53,464][Thread-1:1312][task_id:django.request][log.py:228][WARNING][Not Found: //mock/loginmsg/]
[2019-05-22 14:28:19,728][Thread-1:1312][task_id:django.request][log.py:228][WARNING][Not Found: /mock/user/mock/loginmsg/]
[2019-05-22 14:32:04,524][MainThread:15948][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\settings.py changed, reloading.]
[2019-05-22 14:32:06,628][MainThread:6660][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:33:10,533][MainThread:6660][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:33:12,580][MainThread:19952][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:34:10,344][MainThread:19952][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:34:12,439][MainThread:8336][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:39:58,246][MainThread:15504][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:41:44,014][MainThread:15504][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:41:46,512][MainThread:20100][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:42:09,588][MainThread:20100][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:42:12,017][MainThread:15220][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:42:33,386][MainThread:15220][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\mock_url.py changed, reloading.]
[2019-05-22 14:42:35,581][MainThread:19884][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:43:49,560][Thread-1:15592][task_id:django.request][log.py:228][WARNING][Not Found: /mock/login]
[2019-05-22 14:44:08,321][Thread-1:15592][task_id:mockapp.views][views.py:59][INFO][登入成功]
[2019-05-22 14:44:51,717][MainThread:19884][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\mock_url.py changed, reloading.]
[2019-05-22 14:44:53,829][MainThread:10728][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:45:04,157][Thread-1:18968][task_id:django.request][log.py:228][WARNING][Not Found: /mock/login/]
[2019-05-22 14:45:13,217][Thread-1:18968][task_id:django.request][log.py:228][WARNING][Not Found: /mock/login]
[2019-05-22 14:45:41,581][MainThread:10728][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\mock_url.py changed, reloading.]
[2019-05-22 14:45:43,763][MainThread:12964][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:45:53,445][Thread-1:2424][task_id:mockapp.views][views.py:59][INFO][登入成功]
[2019-05-22 14:45:58,219][Thread-1:2424][task_id:django.request][log.py:228][WARNING][Not Found: /mock/login/]
[2019-05-22 14:50:33,727][Thread-1:2424][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/user/query]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 83, in query_by_name
    return success_jsonresponse("查询成功",100000,data=user)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 11, in success_jsonresponse
    jsonstr = json.dumps(responsedict,ensure_ascii=False)
  File "C:\python\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\python\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable
[2019-05-22 14:53:18,212][MainThread:8160][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:53:25,335][Thread-1:7088][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/user/query]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 89, in query_by_name
    return success_jsonresponse("查询成功",100000,data=user)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 13, in success_jsonresponse
    jsonstr = json.dumps(responsedict,ensure_ascii=False)
  File "C:\python\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\python\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable
[2019-05-22 14:54:27,806][MainThread:8160][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:54:29,893][MainThread:16448][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:54:45,130][Thread-1:6648][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/user/query]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 84, in query_by_name
    return success_jsonresponse("查询成功",100000,data=user)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 22, in success_jsonresponse
    jsonstr = json.dumps(responsedict,ensure_ascii=False)
  File "C:\python\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\python\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable
[2019-05-22 14:55:18,180][MainThread:16448][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\utils\common.py changed, reloading.]
[2019-05-22 14:55:20,117][MainThread:14056][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:55:27,882][Thread-1:13632][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/user/query]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 84, in query_by_name
    return success_jsonresponse("查询成功",100000,data=user)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 22, in success_jsonresponse
    jsonstr = json.dumps(responsedict,ensure_ascii=False)
  File "C:\python\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\python\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable
[2019-05-22 14:55:59,645][MainThread:14056][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\utils\common.py changed, reloading.]
[2019-05-22 14:56:02,012][MainThread:18160][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:56:16,682][MainThread:18160][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\utils\common.py changed, reloading.]
[2019-05-22 14:56:18,886][MainThread:20028][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 14:56:55,848][Thread-1:11704][task_id:mockapp.views][views.py:76][INFO][查询成功]
[2019-05-22 14:59:31,380][MainThread:20028][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 14:59:33,719][MainThread:788][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:02:34,974][MainThread:788][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 15:02:37,789][MainThread:8128][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:06:49,121][MainThread:8128][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 15:06:51,284][MainThread:19548][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:08:29,838][MainThread:19548][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 15:08:32,692][MainThread:19336][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:09:09,383][MainThread:19336][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\mock_url.py changed, reloading.]
[2019-05-22 15:09:11,921][MainThread:19024][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:09:33,640][Thread-1:6244][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/logout]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 71, in logout
    return success_jsonresponse("注销成功",100000)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 20, in success_jsonresponse
    data = object_to_json(data)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 38, in object_to_json
    return dict([(kk, obj.__dict__[kk]) for kk in obj.__dict__.keys() if kk != "_state"])
AttributeError: 'NoneType' object has no attribute '__dict__'
[2019-05-22 15:11:33,741][MainThread:19024][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 15:11:35,929][MainThread:14860][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:12:01,537][MainThread:14860][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\views.py changed, reloading.]
[2019-05-22 15:12:04,070][MainThread:18676][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:12:08,849][Thread-1:19744][task_id:django.request][log.py:228][ERROR][Internal Server Error: /mock/logout]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 72, in logout
    return success_jsonresponse("注销成功", 100000)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 20, in success_jsonresponse
    data = object_to_json(data)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 38, in object_to_json
    return dict([(kk, obj.__dict__[kk]) for kk in obj.__dict__.keys() if kk != "_state"])
AttributeError: 'NoneType' object has no attribute '__dict__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\djcps\Desktop\mock\mock\mockapp\views.py", line 74, in logout
    return fail_jsonresponse("你已经注销了哦",100000)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 30, in fail_jsonresponse
    data = object_to_json(data)
  File "C:\Users\djcps\Desktop\mock\mock\utils\common.py", line 38, in object_to_json
    return dict([(kk, obj.__dict__[kk]) for kk in obj.__dict__.keys() if kk != "_state"])
AttributeError: 'NoneType' object has no attribute '__dict__'
[2019-05-22 15:13:35,882][MainThread:18676][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\utils\common.py changed, reloading.]
[2019-05-22 15:13:38,171][MainThread:19368][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:26:44,198][MainThread:19368][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 15:26:46,575][MainThread:13368][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:26:52,796][MainThread:13368][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 15:26:55,431][MainThread:19928][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:26:59,210][MainThread:19928][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 15:27:02,061][MainThread:18132][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:27:14,649][MainThread:18132][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 15:27:16,720][MainThread:16584][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:27:45,057][Thread-1:3804][task_id:django.request][log.py:228][ERROR][Internal Server Error: /docs]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\urls\base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'rest_framework'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework\response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 54, in render
    self.set_context(data, renderer_context)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 64, in set_context
    renderer_context.update(self.get_auth_urls())
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 76, in get_auth_urls
    urls['LOGIN_URL'] = resolve_url(settings.LOGIN_URL)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\shortcuts.py", line 148, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'rest_framework' is not a registered namespace
[2019-05-22 15:31:09,145][MainThread:16584][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\settings.py changed, reloading.]
[2019-05-22 15:31:12,476][MainThread:3392][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:31:26,163][Thread-3:16444][task_id:django.request][log.py:228][ERROR][Internal Server Error: /docs]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\urls\base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'rest_framework'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework\response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 54, in render
    self.set_context(data, renderer_context)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 64, in set_context
    renderer_context.update(self.get_auth_urls())
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 76, in get_auth_urls
    urls['LOGIN_URL'] = resolve_url(settings.LOGIN_URL)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\shortcuts.py", line 148, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'rest_framework' is not a registered namespace
[2019-05-22 15:32:00,858][MainThread:3392][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\settings.py changed, reloading.]
[2019-05-22 15:32:03,091][MainThread:6920][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:35:51,799][MainThread:6920][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 15:35:53,934][MainThread:9148][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:36:19,575][MainThread:9148][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 15:36:21,615][MainThread:16880][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:42:04,191][MainThread:20252][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:42:08,555][Thread-3:20380][task_id:django.request][log.py:228][ERROR][Internal Server Error: /docs]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\urls\base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'rest_framework'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework\response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 54, in render
    self.set_context(data, renderer_context)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 64, in set_context
    renderer_context.update(self.get_auth_urls())
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 76, in get_auth_urls
    urls['LOGIN_URL'] = resolve_url(settings.LOGIN_URL)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\shortcuts.py", line 148, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'rest_framework' is not a registered namespace
[2019-05-22 15:42:41,409][MainThread:20252][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 15:42:43,650][MainThread:8552][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:43:55,374][MainThread:8552][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 15:43:57,659][MainThread:17944][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:45:06,582][MainThread:12968][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:47:41,700][MainThread:12968][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\settings.py changed, reloading.]
[2019-05-22 15:47:43,643][MainThread:6244][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 15:48:46,146][Thread-3:18504][task_id:django.request][log.py:228][ERROR][Internal Server Error: /docs]
Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\urls\base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'rest_framework'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework\response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 54, in render
    self.set_context(data, renderer_context)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 64, in set_context
    renderer_context.update(self.get_auth_urls())
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\rest_framework_swagger\renderers.py", line 76, in get_auth_urls
    urls['LOGIN_URL'] = resolve_url(settings.LOGIN_URL)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\shortcuts.py", line 148, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\djcps\Desktop\mock\venv\lib\site-packages\django\urls\base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'rest_framework' is not a registered namespace
[2019-05-22 16:14:27,626][MainThread:6244][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\settings.py changed, reloading.]
[2019-05-22 16:14:29,861][MainThread:19252][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:15:55,228][MainThread:19252][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:15:57,635][MainThread:8316][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:17:07,542][Thread-1:18316][task_id:django.request][log.py:228][WARNING][Not Acceptable: /docs]
[2019-05-22 16:17:19,351][Thread-1:18316][task_id:django.security.csrf][log.py:228][WARNING][Forbidden (CSRF cookie not set.): /^api-auth/login/]
[2019-05-22 16:18:45,720][MainThread:8316][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:18:47,860][MainThread:3196][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:20:13,463][MainThread:3196][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:20:15,646][MainThread:12664][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:20:30,073][MainThread:12664][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:20:32,062][MainThread:8612][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:20:50,634][MainThread:8612][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:20:52,677][MainThread:14632][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:21:23,912][MainThread:14632][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:21:26,169][MainThread:17968][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:21:37,412][MainThread:17968][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:21:39,672][MainThread:8296][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:21:51,233][MainThread:8296][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:21:53,402][MainThread:18080][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:22:31,957][MainThread:18080][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:22:34,554][MainThread:18944][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:22:39,702][Thread-3:19016][task_id:django.request][log.py:228][WARNING][Forbidden: /docs]
[2019-05-22 16:22:52,840][Thread-3:19016][task_id:django.request][log.py:228][WARNING][Forbidden: /docs]
[2019-05-22 16:22:54,677][Thread-3:19016][task_id:django.request][log.py:228][WARNING][Not Found: /docs]
[2019-05-22 16:23:01,418][Thread-3:19016][task_id:django.request][log.py:228][WARNING][Forbidden: /docs]
[2019-05-22 16:23:28,468][MainThread:18944][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:23:30,479][MainThread:10300][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:23:36,785][Thread-3:17992][task_id:django.request][log.py:228][WARNING][Forbidden: /docs]
[2019-05-22 16:23:37,494][Thread-3:17992][task_id:django.request][log.py:228][WARNING][Forbidden: /docs]
[2019-05-22 16:23:57,246][Thread-3:17992][task_id:django.request][log.py:228][WARNING][Forbidden: /docs]
[2019-05-22 16:23:57,876][MainThread:10300][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 16:24:00,065][MainThread:19604][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:31:44,795][Thread-6:20392][task_id:django.request][log.py:228][WARNING][Not Found: /favicon.ico]
[2019-05-22 16:32:47,568][Thread-6:20392][task_id:django.request][log.py:228][WARNING][Not Acceptable: /docs]
[2019-05-22 16:33:12,869][Thread-6:20392][task_id:django.request][log.py:228][WARNING][Not Acceptable: /docs]
[2019-05-22 16:37:47,040][Thread-6:20392][task_id:django.security.csrf][log.py:228][WARNING][Forbidden (CSRF cookie not set.): /^api-auth/login/]
[2019-05-22 16:38:44,367][MainThread:19604][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\settings.py changed, reloading.]
[2019-05-22 16:38:46,791][MainThread:5492][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 16:39:27,068][Thread-1:17240][task_id:django.request][log.py:228][WARNING][Not Found: /mock/loginmsg/]
[2019-05-22 16:40:53,429][MainThread:5492][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\settings.py changed, reloading.]
[2019-05-22 16:40:55,638][MainThread:11584][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 17:00:20,232][MainThread:11584][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\urls.py changed, reloading.]
[2019-05-22 17:00:22,374][MainThread:21092][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-22 17:58:34,138][MainThread:21092][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mock\settings.py changed, reloading.]
[2019-05-22 17:58:36,336][MainThread:17660][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-23 16:28:43,068][MainThread:19100][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-23 16:29:23,489][Thread-3:16576][task_id:django.request][log.py:228][WARNING][Not Found: /favicon.ico]
[2019-05-23 16:29:49,302][Thread-3:16576][task_id:django.request][log.py:228][WARNING][Not Acceptable: /docs]
[2019-05-23 16:30:07,696][Thread-3:16576][task_id:django.request][log.py:228][WARNING][Not Found: /mock/loginmsg/]
[2019-05-23 16:31:42,367][MainThread:19100][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\mock_url.py changed, reloading.]
[2019-05-23 16:31:45,552][MainThread:18576][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
[2019-05-23 16:31:47,671][Thread-1:12832][task_id:django.request][log.py:228][WARNING][Not Found: /mock/loginmsg/]
[2019-05-23 16:32:05,255][Thread-1:12832][task_id:django.request][log.py:228][WARNING][Not Found: /mock/loginmsg/]
[2019-05-23 16:32:05,877][MainThread:18576][task_id:django.utils.autoreload][autoreload.py:203][INFO][C:\Users\djcps\Desktop\mock\mock\mockapp\mock_url.py changed, reloading.]
[2019-05-23 16:32:09,094][MainThread:4652][task_id:django.utils.autoreload][autoreload.py:576][INFO][Watching for file changes with StatReloader]
